services:

  minecraft:

    build: .

    container_name: minecraft-server

    restart: unless-stopped

    ports:
      - "25565:25565"

    env_file:
      - .env

    volumes:
      - ./data:/data
      - ./runtime:/runtime

    platform: linux/amd64
    
    stop_grace_period: 60s